"""initial_schema

Revision ID: 08073a365dc9
Revises: 
Create Date: 2026-03-10 18:50:34.574758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08073a365dc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_reason', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('matched_cases', sa.JSON(), nullable=True),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_lob_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_apollo_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('letter_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_address'), 'leads', ['address'], unique=False)
    op.create_index(op.f('ix_leads_call_due_at'), 'leads', ['call_due_at'], unique=False)
    op.create_index(op.f('ix_leads_sent_apollo_at'), 'leads', ['sent_apollo_at'], unique=False)
    op.create_index(op.f('ix_leads_sent_lob_at'), 'leads', ['sent_lob_at'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('mbp_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('jurisdictions', sa.String(), nullable=True),
    sa.Column('days_back', sa.Integer(), nullable=True),
    sa.Column('date_from_str', sa.String(), nullable=True),
    sa.Column('date_to_str', sa.String(), nullable=True),
    sa.Column('total_permits', sa.Integer(), nullable=True),
    sa.Column('analyzed_count', sa.Integer(), nullable=True),
    sa.Column('owner_builders_found', sa.Integer(), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('current_jurisdiction', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbp_jobs_id'), 'mbp_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_mbp_jobs_status'), 'mbp_jobs', ['status'], unique=False)
    op.create_table('permit_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('permit_class_filter', sa.String(), nullable=True),
    sa.Column('permit_type_filter', sa.String(), nullable=True),
    sa.Column('min_cost', sa.Float(), nullable=True),
    sa.Column('permits_found', sa.Integer(), nullable=True),
    sa.Column('permits_verified', sa.Integer(), nullable=True),
    sa.Column('owner_builders_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_jobs_id'), 'permit_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_permit_jobs_status'), 'permit_jobs', ['status'], unique=False)
    op.create_table('recorder_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type_code', sa.String(), nullable=True),
    sa.Column('doc_type_value', sa.String(), nullable=True),
    sa.Column('doc_type_text', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('parcel', sa.String(), nullable=True),
    sa.Column('recording_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('grantor_name', sa.String(), nullable=True),
    sa.Column('grantee_name', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recorder_documents_address'), 'recorder_documents', ['address'], unique=False)
    op.create_index(op.f('ix_recorder_documents_id'), 'recorder_documents', ['id'], unique=False)
    op.create_index(op.f('ix_recorder_documents_parsed_at'), 'recorder_documents', ['parsed_at'], unique=False)
    op.create_index(op.f('ix_recorder_documents_recording_date'), 'recorder_documents', ['recording_date'], unique=False)
    op.create_table('zillow_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urls', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_url_index', sa.Integer(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('homes_found', sa.Integer(), nullable=True),
    sa.Column('unique_homes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zillow_jobs_id'), 'zillow_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_zillow_jobs_status'), 'zillow_jobs', ['status'], unique=False)
    op.create_table('zillow_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zpid', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zillow_status_history_checked_at'), 'zillow_status_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_zillow_status_history_id'), 'zillow_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_zillow_status_history_status'), 'zillow_status_history', ['status'], unique=False)
    op.create_index(op.f('ix_zillow_status_history_zpid'), 'zillow_status_history', ['zpid'], unique=False)
    op.create_table('mbp_permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('permit_number', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permit_type', sa.String(), nullable=True),
    sa.Column('permit_status', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('parcel', sa.String(), nullable=True),
    sa.Column('applied_date', sa.String(), nullable=True),
    sa.Column('issued_date', sa.String(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('contractor_license', sa.String(), nullable=True),
    sa.Column('is_owner_builder', sa.Boolean(), nullable=True),
    sa.Column('matches_target_type', sa.Boolean(), nullable=True),
    sa.Column('permit_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['mbp_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbp_permits_id'), 'mbp_permits', ['id'], unique=False)
    op.create_index(op.f('ix_mbp_permits_is_owner_builder'), 'mbp_permits', ['is_owner_builder'], unique=False)
    op.create_index(op.f('ix_mbp_permits_job_id'), 'mbp_permits', ['job_id'], unique=False)
    op.create_index(op.f('ix_mbp_permits_jurisdiction'), 'mbp_permits', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_mbp_permits_permit_number'), 'mbp_permits', ['permit_number'], unique=False)
    op.create_table('outbound_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_log_id'), 'outbound_log', ['id'], unique=False)
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('permit_num', sa.String(), nullable=False),
    sa.Column('permit_class', sa.String(), nullable=True),
    sa.Column('permit_class_mapped', sa.String(), nullable=True),
    sa.Column('permit_type_mapped', sa.String(), nullable=True),
    sa.Column('permit_type_desc', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('est_project_cost', sa.Float(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('status_current', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('is_owner_builder', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('work_performer_text', sa.String(), nullable=True),
    sa.Column('contacts_text', sa.String(), nullable=True),
    sa.Column('portal_link', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['permit_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permits_applied_date'), 'permits', ['applied_date'], unique=False)
    op.create_index(op.f('ix_permits_city'), 'permits', ['city'], unique=False)
    op.create_index(op.f('ix_permits_id'), 'permits', ['id'], unique=False)
    op.create_index(op.f('ix_permits_is_owner_builder'), 'permits', ['is_owner_builder'], unique=False)
    op.create_index(op.f('ix_permits_job_id'), 'permits', ['job_id'], unique=False)
    op.create_index(op.f('ix_permits_permit_num'), 'permits', ['permit_num'], unique=True)
    op.create_table('zillow_homes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('zpid', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_formatted', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('home_type', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('date_sold', sa.String(), nullable=True),
    sa.Column('sold_date_text', sa.String(), nullable=True),
    sa.Column('zestimate', sa.Float(), nullable=True),
    sa.Column('tax_assessed_value', sa.Float(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('detail_url', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['zillow_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zillow_homes_city'), 'zillow_homes', ['city'], unique=False)
    op.create_index(op.f('ix_zillow_homes_id'), 'zillow_homes', ['id'], unique=False)
    op.create_index(op.f('ix_zillow_homes_job_id'), 'zillow_homes', ['job_id'], unique=False)
    op.create_index(op.f('ix_zillow_homes_price'), 'zillow_homes', ['price'], unique=False)
    op.create_index(op.f('ix_zillow_homes_zpid'), 'zillow_homes', ['zpid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zillow_homes_zpid'), table_name='zillow_homes')
    op.drop_index(op.f('ix_zillow_homes_price'), table_name='zillow_homes')
    op.drop_index(op.f('ix_zillow_homes_job_id'), table_name='zillow_homes')
    op.drop_index(op.f('ix_zillow_homes_id'), table_name='zillow_homes')
    op.drop_index(op.f('ix_zillow_homes_city'), table_name='zillow_homes')
    op.drop_table('zillow_homes')
    op.drop_index(op.f('ix_permits_permit_num'), table_name='permits')
    op.drop_index(op.f('ix_permits_job_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_is_owner_builder'), table_name='permits')
    op.drop_index(op.f('ix_permits_id'), table_name='permits')
    op.drop_index(op.f('ix_permits_city'), table_name='permits')
    op.drop_index(op.f('ix_permits_applied_date'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_outbound_log_id'), table_name='outbound_log')
    op.drop_table('outbound_log')
    op.drop_index(op.f('ix_mbp_permits_permit_number'), table_name='mbp_permits')
    op.drop_index(op.f('ix_mbp_permits_jurisdiction'), table_name='mbp_permits')
    op.drop_index(op.f('ix_mbp_permits_job_id'), table_name='mbp_permits')
    op.drop_index(op.f('ix_mbp_permits_is_owner_builder'), table_name='mbp_permits')
    op.drop_index(op.f('ix_mbp_permits_id'), table_name='mbp_permits')
    op.drop_table('mbp_permits')
    op.drop_index(op.f('ix_zillow_status_history_zpid'), table_name='zillow_status_history')
    op.drop_index(op.f('ix_zillow_status_history_status'), table_name='zillow_status_history')
    op.drop_index(op.f('ix_zillow_status_history_id'), table_name='zillow_status_history')
    op.drop_index(op.f('ix_zillow_status_history_checked_at'), table_name='zillow_status_history')
    op.drop_table('zillow_status_history')
    op.drop_index(op.f('ix_zillow_jobs_status'), table_name='zillow_jobs')
    op.drop_index(op.f('ix_zillow_jobs_id'), table_name='zillow_jobs')
    op.drop_table('zillow_jobs')
    op.drop_index(op.f('ix_recorder_documents_recording_date'), table_name='recorder_documents')
    op.drop_index(op.f('ix_recorder_documents_parsed_at'), table_name='recorder_documents')
    op.drop_index(op.f('ix_recorder_documents_id'), table_name='recorder_documents')
    op.drop_index(op.f('ix_recorder_documents_address'), table_name='recorder_documents')
    op.drop_table('recorder_documents')
    op.drop_index(op.f('ix_permit_jobs_status'), table_name='permit_jobs')
    op.drop_index(op.f('ix_permit_jobs_id'), table_name='permit_jobs')
    op.drop_table('permit_jobs')
    op.drop_index(op.f('ix_mbp_jobs_status'), table_name='mbp_jobs')
    op.drop_index(op.f('ix_mbp_jobs_id'), table_name='mbp_jobs')
    op.drop_table('mbp_jobs')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_sent_lob_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_sent_apollo_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_call_due_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_address'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
